apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: app
    context: app
    requires:
    - image: base
      alias: BASE
  - image: base
    context: base
manifests:
  rawYaml:
  - app/k8s-pod.yaml

