apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
  - image: test-file-sync
    jib:
      type: maven
      args: 
      - --no-transfer-progress
      - -Psync
      fromImage: gcr.io/distroless/java:debug
    sync:
      auto: true

portForward:
- resourceType: pod
  resourceName: test-file-sync
  port: 8080
