apiVersion: skaffold/v4beta12
kind: Config
build:
  artifacts:
  - image: test-file-sync
    jib:
      type: gradle
      args: 
      - -Psync
      - --stacktrace
      - --info
      fromImage: gcr.io/distroless/java21-debian12:debug
    sync:
      auto: true

portForward:
- resourceType: pod
  resourceName: test-file-sync
  port: 8080
