apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: test-file-sync
    sync:
      auto: true
    jib:
      args:
      - -Psync
      type: gradle
      fromImage: gcr.io/distroless/java:debug
portForward:
- resourceType: pod
  resourceName: test-file-sync
  port: 8080
