name: Add new bugs to triage project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to triage project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/letsencrypt/projects/6
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
