apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpacks:
      env:
      - GOOGLE_RUNTIME_VERSION=8
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
