apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: skaffold-examples-buildx
    custom:
      buildCommand: sh buildx.sh
      dependencies:
        paths:
        - "**/*.go"
        - buildx.sh
        - go.mod
  tagPolicy:
    sha256: {}
