apiVersion: skaffold/v4beta13
kind: Config
build:
  googleCloudBuild:
    projectId: skaffold-ci-cd
  artifacts:
  - image: skaffold-example
    kaniko:
      cache: {}
manifests:
  rawYaml:
  - k8s-*
