apiVersion: skaffold/v4beta13
kind: Config
build:
  googleCloudBuild:
    projectId: k8s-skaffold
  artifacts:
  - image: skaffold-example
    kaniko:
      cache: {}
  cluster:
    timeout: 60m
manifests:
  rawYaml:
  - k8s-*
