apiVersion: skaffold/v2beta27
kind: Config
build:
  googleCloudBuild:
    # Change `k8s-skaffold` with your PROJECT_ID
    projectId: k8s-skaffold
  artifacts:
  - image: skaffold-example
    kaniko:
      cache: {}
      image: gcr.io/kaniko-project/executor:v1.6.0
deploy:
  kubectl:
    manifests:
      - k8s-*
