apiVersion: skaffold/v4beta13
kind: Config
build:
  googleCloudBuild:
    projectId: k8s-skaffold
  artifacts:
  - image: skaffold-example
    kaniko:
      useNewRun: true # Speed optimization
      cache: {}
manifests:
  rawYaml:
  - k8s-*
