apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: hello
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: skaffold-bazel
      bazel:
        target: //:skaffold-example.tar
        platforms:
          - platform: linux/amd64
            target: "@rules_go//go/toolchain:linux_amd64"
          - platform: linux/arm64
            target: "@rules_go//go/toolchain:linux_arm64"
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - "deploy.yaml"
