apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: hello
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: hello-image
      bazel:
        target: //:hello.tar
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - "deploy.yaml"
