// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SkaffoldV3ServiceClient is the client API for SkaffoldV3Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkaffoldV3ServiceClient interface {
	// Returns the state of the current Skaffold execution
	GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*State, error)
	// Returns all the events of the current Skaffold execution from the start
	Events(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (SkaffoldV3Service_EventsClient, error)
	// Returns all the user application logs of the current Skaffold execution
	ApplicationLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (SkaffoldV3Service_ApplicationLogsClient, error)
	// Allows for a single execution of some or all of the phases (build, sync, deploy) in case autoBuild, autoDeploy or autoSync are disabled.
	Execute(ctx context.Context, in *UserIntentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Allows for enabling or disabling automatic build trigger
	AutoBuild(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Allows for enabling or disabling automatic sync trigger
	AutoSync(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Allows for enabling or disabling automatic deploy trigger
	AutoDeploy(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// EXPERIMENTAL. It allows for custom events to be implemented in custom builders for example.
	Handle(ctx context.Context, in *Event, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type skaffoldV3ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkaffoldV3ServiceClient(cc grpc.ClientConnInterface) SkaffoldV3ServiceClient {
	return &skaffoldV3ServiceClient{cc}
}

func (c *skaffoldV3ServiceClient) GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/proto.v3.SkaffoldV3Service/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skaffoldV3ServiceClient) Events(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (SkaffoldV3Service_EventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SkaffoldV3Service_ServiceDesc.Streams[0], "/proto.v3.SkaffoldV3Service/Events", opts...)
	if err != nil {
		return nil, err
	}
	x := &skaffoldV3ServiceEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SkaffoldV3Service_EventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type skaffoldV3ServiceEventsClient struct {
	grpc.ClientStream
}

func (x *skaffoldV3ServiceEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *skaffoldV3ServiceClient) ApplicationLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (SkaffoldV3Service_ApplicationLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SkaffoldV3Service_ServiceDesc.Streams[1], "/proto.v3.SkaffoldV3Service/ApplicationLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &skaffoldV3ServiceApplicationLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SkaffoldV3Service_ApplicationLogsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type skaffoldV3ServiceApplicationLogsClient struct {
	grpc.ClientStream
}

func (x *skaffoldV3ServiceApplicationLogsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *skaffoldV3ServiceClient) Execute(ctx context.Context, in *UserIntentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.v3.SkaffoldV3Service/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skaffoldV3ServiceClient) AutoBuild(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.v3.SkaffoldV3Service/AutoBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skaffoldV3ServiceClient) AutoSync(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.v3.SkaffoldV3Service/AutoSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skaffoldV3ServiceClient) AutoDeploy(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.v3.SkaffoldV3Service/AutoDeploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skaffoldV3ServiceClient) Handle(ctx context.Context, in *Event, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.v3.SkaffoldV3Service/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkaffoldV3ServiceServer is the server API for SkaffoldV3Service service.
// All implementations should embed UnimplementedSkaffoldV3ServiceServer
// for forward compatibility
type SkaffoldV3ServiceServer interface {
	// Returns the state of the current Skaffold execution
	GetState(context.Context, *emptypb.Empty) (*State, error)
	// Returns all the events of the current Skaffold execution from the start
	Events(*emptypb.Empty, SkaffoldV3Service_EventsServer) error
	// Returns all the user application logs of the current Skaffold execution
	ApplicationLogs(*emptypb.Empty, SkaffoldV3Service_ApplicationLogsServer) error
	// Allows for a single execution of some or all of the phases (build, sync, deploy) in case autoBuild, autoDeploy or autoSync are disabled.
	Execute(context.Context, *UserIntentRequest) (*emptypb.Empty, error)
	// Allows for enabling or disabling automatic build trigger
	AutoBuild(context.Context, *TriggerRequest) (*emptypb.Empty, error)
	// Allows for enabling or disabling automatic sync trigger
	AutoSync(context.Context, *TriggerRequest) (*emptypb.Empty, error)
	// Allows for enabling or disabling automatic deploy trigger
	AutoDeploy(context.Context, *TriggerRequest) (*emptypb.Empty, error)
	// EXPERIMENTAL. It allows for custom events to be implemented in custom builders for example.
	Handle(context.Context, *Event) (*emptypb.Empty, error)
}

// UnimplementedSkaffoldV3ServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSkaffoldV3ServiceServer struct {
}

func (UnimplementedSkaffoldV3ServiceServer) GetState(context.Context, *emptypb.Empty) (*State, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedSkaffoldV3ServiceServer) Events(*emptypb.Empty, SkaffoldV3Service_EventsServer) error {
	return status.Errorf(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedSkaffoldV3ServiceServer) ApplicationLogs(*emptypb.Empty, SkaffoldV3Service_ApplicationLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method ApplicationLogs not implemented")
}
func (UnimplementedSkaffoldV3ServiceServer) Execute(context.Context, *UserIntentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedSkaffoldV3ServiceServer) AutoBuild(context.Context, *TriggerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoBuild not implemented")
}
func (UnimplementedSkaffoldV3ServiceServer) AutoSync(context.Context, *TriggerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoSync not implemented")
}
func (UnimplementedSkaffoldV3ServiceServer) AutoDeploy(context.Context, *TriggerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoDeploy not implemented")
}
func (UnimplementedSkaffoldV3ServiceServer) Handle(context.Context, *Event) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}

// UnsafeSkaffoldV3ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkaffoldV3ServiceServer will
// result in compilation errors.
type UnsafeSkaffoldV3ServiceServer interface {
	mustEmbedUnimplementedSkaffoldV3ServiceServer()
}

func RegisterSkaffoldV3ServiceServer(s grpc.ServiceRegistrar, srv SkaffoldV3ServiceServer) {
	s.RegisterService(&SkaffoldV3Service_ServiceDesc, srv)
}

func _SkaffoldV3Service_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkaffoldV3ServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v3.SkaffoldV3Service/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkaffoldV3ServiceServer).GetState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkaffoldV3Service_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SkaffoldV3ServiceServer).Events(m, &skaffoldV3ServiceEventsServer{stream})
}

type SkaffoldV3Service_EventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type skaffoldV3ServiceEventsServer struct {
	grpc.ServerStream
}

func (x *skaffoldV3ServiceEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _SkaffoldV3Service_ApplicationLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SkaffoldV3ServiceServer).ApplicationLogs(m, &skaffoldV3ServiceApplicationLogsServer{stream})
}

type SkaffoldV3Service_ApplicationLogsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type skaffoldV3ServiceApplicationLogsServer struct {
	grpc.ServerStream
}

func (x *skaffoldV3ServiceApplicationLogsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _SkaffoldV3Service_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkaffoldV3ServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v3.SkaffoldV3Service/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkaffoldV3ServiceServer).Execute(ctx, req.(*UserIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkaffoldV3Service_AutoBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkaffoldV3ServiceServer).AutoBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v3.SkaffoldV3Service/AutoBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkaffoldV3ServiceServer).AutoBuild(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkaffoldV3Service_AutoSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkaffoldV3ServiceServer).AutoSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v3.SkaffoldV3Service/AutoSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkaffoldV3ServiceServer).AutoSync(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkaffoldV3Service_AutoDeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkaffoldV3ServiceServer).AutoDeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v3.SkaffoldV3Service/AutoDeploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkaffoldV3ServiceServer).AutoDeploy(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkaffoldV3Service_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkaffoldV3ServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v3.SkaffoldV3Service/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkaffoldV3ServiceServer).Handle(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// SkaffoldV3Service_ServiceDesc is the grpc.ServiceDesc for SkaffoldV3Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkaffoldV3Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v3.SkaffoldV3Service",
	HandlerType: (*SkaffoldV3ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _SkaffoldV3Service_GetState_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _SkaffoldV3Service_Execute_Handler,
		},
		{
			MethodName: "AutoBuild",
			Handler:    _SkaffoldV3Service_AutoBuild_Handler,
		},
		{
			MethodName: "AutoSync",
			Handler:    _SkaffoldV3Service_AutoSync_Handler,
		},
		{
			MethodName: "AutoDeploy",
			Handler:    _SkaffoldV3Service_AutoDeploy_Handler,
		},
		{
			MethodName: "Handle",
			Handler:    _SkaffoldV3Service_Handle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _SkaffoldV3Service_Events_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ApplicationLogs",
			Handler:       _SkaffoldV3Service_ApplicationLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v3/skaffold.proto",
}
