steps:
- id: Get github token.
  name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args: [ '-c', "gcloud secrets versions access latest --secret=$_GITHUB_TOKEN --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
- id: Check vulnerability report.
  name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args:
  - ./deploy/binary-vuln-monitor/scan.sh
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - '_IMAGE=$_IMAGE'
  - '_TAG_FILTER=$_TAG_FILTER'
- id: Report vulnerability.
  name: 'gcr.io/$PROJECT_ID/github'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    if test -f /workspace/skaffold_vuln.txt; then ./deploy/binary-vuln-monitor/report.sh; fi
  env:
  - '_REPO=$_REPO'
  - '_ISSUE_TITLE_TEMPLATE=$_ISSUE_TEMPLATE'
  - '_ISSUE_CONTENT_TEMPLATE=$_ISSUE_CONTENT_TEMPLATE'
