apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /my-nginx
  name: my-nginx
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|my-nginx'
spec:
  replicas: 3 # kpt-set: ${nginx-replicas}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "nginx:1.16.2" # kpt-set: nginx:${tag}
          ports:
            - protocol: TCP
              containerPort: 80
---
apiVersion: v1
kind: MyKind
metadata: # kpt-merge: /foo
  name: foo
  annotations:
    internal.kpt.dev/upstream-identifier: '|MyKind|default|foo'
environments: # kpt-set: ${env}
  - prod
  - dev
