apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters
  name: setters
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|setters'
data:
  env: |-
    - prod
    - dev
  nginx-replicas: "3"
  tag: 1.16.2
