apiVersion: skaffold/v3
kind: Config
build:
  # only build and deploy "world-service" on main profile
  artifacts:
  - image: skaffold-world
    context: world-service
manifests:
  rawYaml:
    - 'world-service/*.yaml'

profiles:
  - name: minikube-profile
    # automatically activate this profile when current context is "minikube"
    activation:
      - kubeContext: minikube
    build:
      # only build and deploy "hello-service" on minikube profile
      artifacts:
        - image: skaffold-hello
          context: hello-service
    manifests:
      rawYaml:
        - 'hello-service/*.yaml'

  - name: staging-profile
    build:
      # build and deploy both services on "staging"
      artifacts:
        - image: skaffold-hello
          context: hello-service
        - image: skaffold-world
          context: world-service
    manifests:
      rawYaml:
        - '**/*.yaml'
    deploy:
      # use context "staging" for staging-profile
      kubeContext: staging
