apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      artifactOverrides:
        image: skaffold-helm
