apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      setValues:
        image: skaffold-helm