apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: node-example
    context: backend
profiles:
- name: dev
  activation:
  - command: dev
  build:
    artifacts:
    - image: node-example
      context: backend
      sync:
        manual:
        - src: src/**/*.js
          dest: .
      docker:
        buildArgs:
          ENV: development
