apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/node-example
    context: backend
    sync:
      '*.js': .
deploy:
  kubectl:
    manifests:
    - "backend/k8s/**"
