apiVersion: skaffold/v2beta28
kind: Config
build:
  googleCloudBuild:
    # Change `k8s-skaffold` with your PROJECT_ID
    projectId: k8s-skaffold
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
