apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: react-reload
    context: app
    sync:
      manual:
      - src: 'src/components/*'
        dest: .
      - src: 'src/styles/*'
        dest: .
