apiVersion: skaffold/v4beta2
kind: Config
manifests:
  rawYaml:
  - k8s-pod.yaml
  hooks:
    before:
      - host:
          command: ["sh", "-c", "echo pre-render host hook running on $(hostname)!"]
    after:
      - host:
          command: ["sh", "-c", "echo post-render host hook running on $(hostname)!"]
build:
  artifacts:
  - image: hooks-example
    hooks:
      before:
        - command: ["sh", "-c", "./hook.sh"]
          os: [darwin, linux]
          dir: .
        - command: ["cmd.exe", "/C", "hook.bat"]
          os: [windows]
          dir: .
      after:
        - command: ["sh", "-c", "docker images $SKAFFOLD_IMAGE --digests"]
          os: [darwin, linux]
        - command: ["cmd.exe", "/C", "docker images %SKAFFOLD_IMAGE% --digests"]
          os: [windows]
    sync: 
      manual:
        - src: 'hello.txt'
          dest: .
      hooks:
        before:
          - host:
              command: ["sh", "-c", "echo file changes detected: $SKAFFOLD_FILES_ADDED_OR_MODIFIED"]
              os: [darwin, linux]
          - host:
              command: ["cmd.exe", "/C", "echo file changes detected: %SKAFFOLD_FILES_ADDED_OR_MODIFIED%"]
              os: [windows]
        after:
          - container:
              command: ["sh", "-c", "set -x; kill -HUP 1"]
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command: ["sh", "-c", "echo pre-deploy host hook running on $(hostname)!"]
            os: [darwin, linux]
        - container:
            # this will only run when there's a matching container from a previous deploy iteration like in `skaffold dev` 
            command: ["sh", "-c", "echo pre-deploy container hook running on $(hostname)!"]
            containerName: hooks-example*
            podName: hooks-example-deployment*
      after:
        - host:
            command: ["sh", "-c", "echo post-deploy host hook running on $(hostname)!"]
            os: [darwin, linux]
        - container:
            command: ["sh", "-c", "echo post-deploy container hook running on $(hostname)!"]
            containerName: hooks-example* # use a glob pattern to prefix-match the container name and pod name for deployments, stateful-sets, etc.
            podName: hooks-example-deployment*
