apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
    - image: my-image
      context: my-image
manifests:
  rawYaml:
  - my-manifests-*
resourceSelector:
  allow:
    - groupKind: "CustomDeployment.skaffold.dev"
      image: [".*"]
      labels: [".*"]