apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: skaffold-helm
  tagPolicy:
    sha256: {}
manifests:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: skaffold-helm
      skipBuildDependencies: true
deploy:
  helm: {}
