apiVersion: batch/v1
kind: Job
metadata:
  name: my-chart-job
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
spec:
  template:
    spec:
      containers:
        - name: hello-world
          image: hello-world
      restartPolicy: Never
