apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: skaffold-example
test:
  - image: skaffold-example
    structureTests:
      - ./test/*
manifests:
  rawYaml:
    - k8s-*
profiles:
  - name: test
    test:
      - image: skaffold-example
        structureTests:
          - ./test/profile_structure_test.yaml
