# https://github.com/rubenv/sql-migrate#readme
boulder_sa_test:
  dialect: mysql
  datasource: root@tcp(boulder-mysql:3306)/boulder_sa_test?parseTime=true
  dir: boulder_sa

boulder_sa_integration:
  dialect: mysql
  datasource: root@tcp(boulder-mysql:3306)/boulder_sa_integration?parseTime=true
  dir: boulder_sa

incidents_sa_test:
  dialect: mysql
  datasource: root@tcp(boulder-mysql:3306)/incidents_sa_test?parseTime=true
  dir: incidents_sa

incidents_sa_integration:
  dialect: mysql
  datasource: root@tcp(boulder-mysql:3306)/incidents_sa_integration?parseTime=true
  dir: incidents_sa
