apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/node-example
    context: node
    sync:
      '**/*.js': .
  - image: gcr.io/k8s-skaffold/python-reload
    context: python
    sync:
      '**/*.py': .
deploy:
  kubectl:
    manifests:
    - "**/k8s"
