apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
  - image: node-example
    context: node

  - image: python-reload
    context: python

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: node-example
        context: node
        docker:
          buildArgs:
            ENV: development
        sync:
          manual:
          # Sync all the javascript files that are in the src folder
          # with the container src folder
          - src: 'src/**/*.js'
            dest: .
      - image: python-reload
        context: python
        docker:
          buildArgs:
            DEBUG: 1
        sync:
          manual:
          # Sync all the javascript files that are in the src folder
          # with the container src folder
          - src: 'src/**/*.py'
            dest: .
