# using default substitutions, provided by Google Cloud Build
# see: https://cloud.google.com/container-builder/docs/configuring-builds/substitute-variable-values#using_default_substitutions
steps:

  # Build and tag skaffold-deps image using docker with cache-from
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/build_deps:latest-lts'
      - '--cache-from'
      - 'gcr.io/k8s-skaffold/build_deps:latest-lts'
      - '-f'
      - 'deploy/skaffold/Dockerfile.deps.lts'
      - '.'

  # Grab secret credentials from gcp bucket
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: ['deploy/setup-secret.sh','-p', $PROJECT_ID]

  # Build and tag skaffold builder
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/skaffold-builder:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/skaffold-builder:latest'
      - '-f'
      - 'deploy/skaffold/Dockerfile'
      - '.'

  # Build and tag distroless-skaffold image for scanning
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'PROJECT_ID=$PROJECT_ID'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/scanning/skaffold:$TAG_NAME-lts'
      - '-f'
      - 'deploy/skaffold/Dockerfile.skaffold'
      - '.'

  # Do the go build & push the results to GCS
  - name: 'gcr.io/$PROJECT_ID/skaffold-builder:latest'
    args:
      - 'make'
      - 'release-lts'
      - 'VERSION=$TAG_NAME'
      - 'SCANNING_MARKER=$_SCANNING_MARKER'
      - 'RELEASE_BUCKET=$_RELEASE_BUCKET'
      - 'GCP_PROJECT=$PROJECT_ID'

  # Check that skaffold is in the image
  - name: 'gcr.io/$PROJECT_ID/skaffold:$TAG_NAME-lts'
    args:
      - 'skaffold'
      - 'version'

images:
  - 'gcr.io/$PROJECT_ID/skaffold:$TAG_NAME-lts'
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/scanning/skaffold:$TAG_NAME-lts'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1500s