substitutions:
  _LOUHI_TAG_NAME: ""
steps:
# Build and tag skaffold-deps image using docker with cache-from
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/k8s-skaffold/build_deps:latest'
    - '--cache-from'
    - 'gcr.io/k8s-skaffold/build_deps:latest'
    - '-f'
    - 'deploy/skaffold/Dockerfile.deps'
    - '.'

# Grab secret credentials from gcp bucket
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: ['deploy/setup-secret.sh','-p', 'k8s-skaffold']

# Build and tag skaffold builder
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/k8s-skaffold/skaffold-builder:latest'
    - '-f'
    - 'deploy/skaffold/Dockerfile'
    - '.'

# Do the image build
  - name: 'gcr.io/k8s-skaffold/skaffold-builder:latest'
    args:
    - 'docker'
    - 'build'
    - '--build-arg'
    - 'VERSION=$_LOUHI_TAG_NAME'
    - '-f'
    - 'deploy/skaffold/Dockerfile'
    - '--target'
    - 'release'
    - '-t'
    - 'us-docker.pkg.dev/k8s-skaffold-staging/dev/skaffold:latest'
    - '-t'
    - 'us-docker.pkg.dev/k8s-skaffold-staging/dev/skaffold:$_LOUHI_TAG_NAME'
    - '.'

# Check that skaffold is in the image
  - name: 'us-docker.pkg.dev/k8s-skaffold-staging/dev/skaffold:latest'
    args:
    - 'skaffold'
    - 'version'

images:
# images are stored on dev repo on a staging project.
- 'us-docker.pkg.dev/k8s-skaffold-staging/dev/skaffold:$_LOUHI_TAG_NAME'
- 'us-docker.pkg.dev/k8s-skaffold-staging/dev/skaffold:latest'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1500s
