apiVersion: skaffold/v1alpha5
kind: Config
build:
    artifacts:
    - image: gcr.io/k8s-skaffold/docs-controller
      docker:
        dockerfile: deploy/webhook-v2/Dockerfile
        cacheFrom:
          - gcr.io/k8s-skaffold/docs-controller
deploy:
  kubectl:
    manifests:
      - deploy/webhook-v2/deployment.yaml
