apiVersion: skaffold/v4beta4
kind: Config
build:
  artifacts:
    - image: integration-test-container
      context: integration-test-container
    - image: metrics-test-container
      context: metrics-test-container
verify:
- name: integration-test-container
  container:
    name: integration-test-container
    image: integration-test-container
  executionMode:
    kubernetesCluster: {}
      # [optional]
      # overrides: '{ "apiVersion": "batch/v1", "spec": { ... } }'
- name: metrics-test-container
  container:
    name: metrics-test-container
    image: metrics-test-container
  executionMode:
    kubernetesCluster: {}
      # [optional]
      # jobManifestPath: path/to/my/job
- name: alpine-wget
  container:
    name: alpine-wget
    image: alpine:3.15.4
    command: ["/bin/sh"]
    args: ["-c", "wget http://www.google.com"]

