== Examples
:icons: font

To run the examples, you either have to manually replace the image repositories in the examples from gcr.io/k8s-skaffold to yours or you can point skaffold to your default image repository in one of the four ways:

* flag: `skaffold dev --default-repo <myrepo>`
* env var: `SKAFFOLD_DEFAULT_REPO=<myrepo> skaffold dev`
* global skaffold config (one time): `skaffold config set --global default-repo <myrepo>`
* skaffold config for current kubectl context: `skaffold config set default-repo <myrepo>`

These examples are made to work with the latest release of skaffold.

If you are running skaffold at HEAD or have built it from source, please use the examples at integration/examples.

If you wish to make changes to these examples, please edit the ones at integration/examples, as those will be synced on release.

ifndef::env-github[]

link:{github-repo-tree}/examples[see on Github icon:github[]]

include::./getting-started/README.adoc[]
include::./microservices/README.adoc[]
include::./tagging-with-environment-variables/README.adoc[]
include::./helm-deployment/README.adoc[]
include::./helm-deployment-dependencies/README.adoc[]
include::./kustomize/README.adoc[]
include::./kaniko/README.adoc[]
include::./bazel/README.adoc[]
endif::[]

ifdef::env-github[]

- link:./getting-started[]
- link:./microservices[]
- link:./tagging-with-environment-variables[]
- link:./helm-deployment[]
- link:./helm-deployment-dependencies[]
- link:./kustomize[]
- link:./kaniko[]
- link:./bazel[]

endif::[]
