apiVersion: skaffold/v4beta4
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpacks:
      env:
      - GOPROXY={{.GOPROXY}}
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
