apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
      trustBuilder: true
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
