apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: bert
    context: bert
  - image: ernie
    context: ernie
  local:
    push: false
deploy:
  docker:
    images:
    - bert
    - ernie
