apiVersion: skaffold/v4beta12
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: bert
    context: bert
  - image: ernie
    context: ernie
deploy:
  docker:
    images: [bert, ernie]
