=== Example: Getting started with buildpacks
:icons: font

This is a simple example based on

* *building* a single go file app with buildpacks
* *tagging* using the default tagPolicy (`gitCommit`)
* *deploying* a single container pod using `kubectl`

## Before you begin

For this tutorial to work, you will need to have Skaffold and a Kubernetes cluster set up.
To learn more about how to set up Skaffold and a Kubernetes cluster, see the https://skaffold.dev/docs/getting-started[getting started docs].

To use buildpacks with Skaffold, please install the following additional tools:

* https://buildpacks.io/docs/install-pack/[pack]
* https://docs.docker.com/install/[docker]

## Tutorial

This tutorial will demonstrate how Skaffold can build a simple Hello World Go application with buildpacks and deploy it to a Kubernetes cluster.

First, clone the Skaffold https://github.com/GoogleContainerTools/skaffold[repo] and navigate to the https://github.com/GoogleContainerTools/skaffold/tree/master/examples/buildpacks[buildpacks example] for sample code:

```shell
$ git clone https://github.com/GoogleContainerTools/skaffold
$ cd skaffold/examples/buildpacks
```

Take a look at the `build.sh` file, which uses `pack` to containerize source code with buildpacks:

```shell
$ cat build.sh
#!/usr/bin/env bash
set -e

pack build --builder=heroku/buildpacks $IMAGE

if $PUSH_IMAGE; then
    docker push $IMAGE
fi
```

and the skaffold config, which configures artifact `gcr.io/k8s-skaffold/skaffold-example` to build with `build.sh`:

```yaml
$ cat skaffold.yaml
apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
    custom:
      buildCommand: ./build.sh
```
For more information about how this works, see the Skaffold custom builder https://skaffold.dev/docs/how-tos/builders/#custom-build-script-run-locally[documentation].

Now, use Skaffold to deploy this application to your Kubernetes cluster:

```shell
$ skaffold run --tail --default-repo <your repo>
```

With this command, Skaffold will build the `skaffold-example` artifact with buildpacks and deploy the application to Kubernetes.
You should be able to see "Hello, World!" printed every second in the Skaffold logs.

To clean up your Kubernetes cluster, run:

```shell
$ skaffold delete
```

ifndef::env-github[]
==== link:{github-repo-tree}/examples/buildpacks[Example files icon:github[]]

[source,yaml, indent=3, title=skaffold.yaml]
----
include::skaffold.yaml[]
----

[source,go, indent=3, title=main.go, syntax=go]
----
include::main.go[]
----

[source,yaml, indent=3, title=k8s-pod.yaml]
----
include::k8s-pod.yaml[]
----

endif::[]
