apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: github.com/googlecontainertools/skaffold/examples/custom
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - "go.mod"
        - "**.go"
  tagPolicy:
    sha256: {}
