apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: skaffold-example-1
    context: .
    docker:
      dockerfile: Dockerfile
      noCache: true
  - image: skaffold-example-2
    context: .
    docker:
      dockerfile: Dockerfile
      noCache: true
  tagPolicy:
    - sha256: {}
    - customTemplate:
        template: "secondtag"

  local:
    concurrency: 1
manifests:
  rawYaml:
  - k8s-*
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: {}