apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: skaffold-example
    context: .
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  platforms:
  - linux/amd64
  local:
    concurrency: 1
manifests:
  rawYaml:
  - k8s-*
