apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: skaffold-example
    context: .
    docker:
      dockerfile: Dockerfile
      noCache: true
  tagPolicy:
    # - gitCommit:
    #     variant: CommitSha
    #     prefix: "renzor-"
    - inputDigest: {}
  local:
    concurrency: 1
manifests:
  rawYaml:
  - k8s-*
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: {}