apiVersion: skaffold/v2beta28
kind: Config
build:
  platforms: ["linux/amd64"]
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: googleCloudBuild
    build:
      googleCloudBuild:
        projectId: k8s-skaffold
