apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
    - image: skaffold-example
      kaniko:
        useNewRun: true # Speed optimization
        cache: {}
  cluster:
    pullSecretName: e2esecret
manifests:
  rawYaml:
  - k8s-*
