apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
    - image: skaffold-example
      kaniko:
        cache: {}
        image: gcr.io/kaniko-project/executor:v1.6.0
  cluster:
    pullSecretName: e2esecret-with-path
    pullSecretPath:     kaniko-secret.json
    namespace: default
deploy:
  kubectl:
    manifests:
      - k8s-*
