apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: my-app
build:
  artifacts:
  - image: skaffold-templated
    custom:
      buildCommand: "./build.sh"
      dependencies:
        paths:
        - "**/*.go"
        - go.mod
deploy:
  helm:
    releases:
    - name: skaffold-templated
      chartPath: charts
      artifactOverrides:
        image: skaffold-templated
      setValueTemplates:
        imageRepo: "{{.IMAGE_REPO}}"
        imageTag: "{{.IMAGE_TAG}}"
