apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: go-guestbook-frontend
        ports:
        - name: http-server
          containerPort: 8080
        - name: debug
          containerPort: 3000
        env:
        - name: PORT
<<<<<<< HEAD
          value: "8080"
=======
          value: "27017"
>>>>>>> 14b1e178a (feat: allow multiple mixed in renderers)
        - name: GUESTBOOK_API_ADDR
          value: localhost:27017
