apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: skaffold-world
    context: world-service
manifests:
  rawYaml:
  - world-service/*.yaml
deploy:
  kubectl: {}
profiles:
- name: minikube-profile
  activation:
  - kubeContext: minikube
  build:
    artifacts:
    - image: skaffold-hello
      context: hello-service
  manifests:
    rawYaml:
    - hello-service/*.yaml
  deploy:
    kubectl: {}
- name: staging-profile
  build:
    artifacts:
    - image: skaffold-hello
      context: hello-service
    - image: skaffold-world
      context: world-service
  manifests:
    rawYaml:
    - '**/*.yaml'
  deploy:
    kubectl: {}
    kubeContext: staging
