apiVersion: skaffold/v2beta28
kind: Config
requires:
- git:
    repo: https://github.com/GoogleContainerTools/skaffold
    ref: release/v1.37.4
    path: examples/multi-config-microservices/leeroy-app
    sync: false
- git:
    repo: https://github.com/GoogleContainerTools/skaffold
    ref: release/v1.37.4
    path: examples/multi-config-microservices/leeroy-web
    sync: false
