apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: skaffold-example
  platforms:
  - linux/amd64
manifests:
  rawYaml:
  - k8s-*
deploy:
  kubectl: {}
profiles:
- name: googleCloudBuild
  build:
    googleCloudBuild:
      projectId: k8s-skaffold
