apiVersion: skaffold/v4beta5
kind: Config

customActions:
  - name: update-infra
    containers:
      - name: update-db-schema
        image: gcr.io/my-registry/db-updater:latest
      - name: setup-external-proxy
        image: gcr.io/my-registry/proxy:latest