apiVersion: skaffold/v2beta6
kind: Config
build:
  artifacts:
  - image: test-file-sync
    jib:
      type: maven
      args: 
      - --no-transfer-progress
      - -Psync
    sync:
      auto: {}

portForward:
- resourceType: pod
  resourceName: test-file-sync
  port: 8080
