apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
  - image: skaffold-jib-gradle
    jib:
      type: gradle
      fromImage: gcr.io/distroless/java21-debian12:debug


# optional profile to run the jib build on Google Cloud Build
profiles:
  - name: gcb
    build:
      googleCloudBuild: {
        # gcb doesn't use the gradle wrapper in the application project to build, users need to provide a gradle image
        # that can run all tasks defined in build.gradle file as the default one provided by cloudBuilders might be too
        # old.
        gradleImage: gradle:jdk21-corretto@sha256:06346c0949f4ca2e5e2691504b63528bc55a5745627259e93686fdcdcb565a07
      }
