apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: skaffold-examples-buildx
    custom:
      buildCommand: sh buildx.sh
      dependencies:
        paths:
        - '**/*.go'
        - buildx.sh
        - go.mod
  tagPolicy:
    sha256: {}
  platforms:
  - linux/amd64
  - linux/arm64
