apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: skaffold-example
    kaniko:
      cache: {}
  googleCloudBuild:
    projectId: k8s-skaffold
manifests:
  rawYaml:
  - k8s-*
deploy:
  kubectl: {}
