apiVersion: skaffold/v2beta29
kind: Config
build:
  googleCloudBuild:
    # Change `k8s-skaffold` with your PROJECT_ID
    projectId: k8s-skaffold
  artifacts:
  - image: skaffold-example
    kaniko:
      cache: {}
deploy:
  kubectl:
    manifests:
      - k8s-*
