apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
  kaniko:
    gcsBucket: skaffold-kaniko
    pullSecretName: e2esecret
deploy:
  kubectl:
    manifests:
      - k8s-*
