apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: skaffold-example
    kaniko:
      cache: {}
  cluster:
    namespace: default
    pullSecretName: e2esecret-with-path
    pullSecretPath: kaniko-secret.json
manifests:
  rawYaml:
  - k8s-*
deploy:
  kubectl: {}
