name: PR linters, checks

# Triggers the workflow on push or pull request events
on: [push, pull_request]

permissions: read-all

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{github.workflow}}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: PR linters, checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.*
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Inject base sha and pr sha
        run: |
          GITHUB_BASE_SHA=${{ github.event.pull_request.base.sha }}
          GITHUB_SHA=${{ github.sha }}

      - name: Run make linters
        run: |
          make linters

      - name: Run make checks
        run: |
          make checks