name: PR unit tests (windows)

# Triggers the workflow on push or pull request events
on: [push, pull_request]

permissions: read-all

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{github.workflow}}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:
    name: PR unit tests (windows)
    runs-on: windows-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.*
      id: go

    # Retrieve build locations with `go env`
    # <https://markphelps.me/posts/speed-up-your-go-builds-with-actions-cache/>
    - id: go-cache-paths
      run: |
        echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
        echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v4
      with:
        path: |
          ${{ steps.go-cache-paths.outputs.go-build }}
          ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Remove minikube
      # the preinstalled minikube causes ci broken, and we don't need minikube for unit testing.
      run: |
        choco uninstall minikube -y
      # TODO(aaron-prindle) skip unit tests for doc only changes on Windows.  Figure out the proper syntax, etc.
    - name: Run skaffold unit tests on windows
      run: |
        go test -count=1 -short -timeout 90s  ./pkg/skaffold/... ./cmd/... ./hack/... ./pkg/webhook/...
