apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: node-example
    context: node
  - image: python-reload
    context: python
profiles:
- name: dev
  activation:
  - command: dev
  build:
    artifacts:
    - image: node-example
      context: node
      sync:
        manual:
        - src: src/**/*.js
          dest: .
      docker:
        buildArgs:
          ENV: development
    - image: python-reload
      context: python
      sync:
        manual:
        - src: src/**/*.py
          dest: .
      docker:
        buildArgs:
          DEBUG: "1"
