apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/node-example
    context: node
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
        strip: src/
  - image: gcr.io/k8s-skaffold/python-reload
    context: python
    sync:
      manual:
      - src: 'src/**/*.py'
        dest: .
        strip: src/
